# Generated by Django 4.1.5 on 2023-01-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employename', models.CharField(max_length=30)),
                ('employeid', models.IntegerField()),
                ('companyname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=30)),
            ],
        ),
    ]
