# Generated by Django 4.1.5 on 2023-01-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_employemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='imgmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgname', models.CharField(max_length=30)),
                ('imgfile', models.ImageField(upload_to='newapp/static')),
            ],
        ),
    ]
