# Generated by Django 4.1.5 on 2023-01-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_imgmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='audiomodell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audioname', models.CharField(max_length=30)),
                ('audioimage', models.ImageField(upload_to='newapp/static')),
                ('audiofile', models.FileField(upload_to='newapp/static')),
            ],
        ),
    ]
