# Generated by Django 4.1.5 on 2023-01-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_audiomodell'),
    ]

    operations = [
        migrations.CreateModel(
            name='videomodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoname', models.CharField(max_length=30)),
                ('videofile', models.FileField(upload_to='newapp/static')),
            ],
        ),
    ]
