# Generated by Django 4.1.5 on 2023-01-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_videomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='resumemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employename', models.CharField(max_length=30)),
                ('resume', models.FileField(upload_to='newapp/static')),
            ],
        ),
    ]
