# Generated by Django 4.1.5 on 2023-01-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_resumemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('shopid', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
