# Generated by Django 4.1.5 on 2023-02-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0014_cartbuyss'),
    ]

    operations = [
        migrations.CreateModel(
            name='cusdetailsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholdername', models.CharField(max_length=30)),
                ('cardnumber', models.CharField(max_length=30)),
                ('expiredate', models.CharField(max_length=30)),
                ('securitycode', models.CharField(max_length=30)),
            ],
        ),
    ]
