# Generated by Django 4.1.5 on 2023-02-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0015_cusdetailsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='shopid',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
