# Generated by Django 4.1.5 on 2023-02-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0016_productmodel_shopid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='shopid',
            field=models.IntegerField(),
        ),
    ]
