# Generated by Django 4.1.5 on 2023-02-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0017_alter_productmodel_shopid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='usernme',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
    ]
