# Generated by Django 4.1.5 on 2023-02-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0020_snotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='usnotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('shopnot', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
